plugins {
    id 'fabric-loom' version '${loomVersion}'
    id 'maven-publish'
}

version = '${version}'
group = '${group}'

base {
    archivesName = '${modid}'
}

repositories {
}

dependencies {
    // 官方 Piston 与 Fabric 仓库由 fabric-loom 自动加入
    minecraft 'com.mojang:minecraft:${mcVersion}'
    mappings 'net.fabricmc:yarn:${yarnVersion}:v2'
    modImplementation 'net.fabricmc:fabric-loader:${fabricLoaderVersion}'

    // Fabric API（按需可只引入用到的模块）
    modImplementation 'net.fabricmc.fabric-api:fabric-api:${fabricApiVersion}'
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = ${javaVersion}
}

java {
    withSourcesJar()
}

jar {
    manifest {
        attributes([
                'Implementation-Title'  : '${modid}',
                'Implementation-Version': project.version
        ])
    }
}
